## Pull container images from Docker Hub repository or private repository
FROM ubuntu:20.04

## Install basic Ubuntu tools requirement.
RUN apt-get update && \
    apt-get install -y \
    git \
	vim \
	sudo \
	wget \
	curl \
	apt-utils